orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  docker: circleci/docker@1.6.0
version: 2.1
jobs:
  build_container_image:
    #machine:
    #  image: default
    #docker:
    #  - image: cimg/base:2021.04
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - aws-ecr/build-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${CIRCLE_SHA1},latest
      - run:
          command: |
            docker image ls
      - run:
          name: Install dockle
          command: |
            VERSION=$(
              curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
              grep '"tag_name":' | \
              sed -E 's/.*"v([^"]+)".*/\1/'
            )
            curl -sLO https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
            tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
            sudo mv dockle /usr/local/bin
      - run:
          name: Scan the image with docke
          command: dockle --exit-code 1 --exit-level FATAL ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1}
      - run:
          name: Install trivy
          command: |
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )
            curl -sLO https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            sudo mv trivy /usr/local/bin
      - run:
          name: Scan image with trivy
          command: trivy image --ignore-unfixed --exit-code 1 --no-progress --severity HIGH,CRITICAL ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1}
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${CIRCLE_SHA1},latest
workflows:
  build:
    jobs:
      - build_container_image:
          filters:
            tags:
              ignore: /.*/
      - aws-ecr/build-and-push-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${CIRCLE_TAG}
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
