orbs:
  docker: circleci/docker@1.6.0
  aws-ecr: circleci/aws-ecr@0.0.2
version: 2.1
jobs:
  build_container_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: ${CIRCLE_SHA1}
  build_and_push:
    executor: docker/docker
    steps:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: ${CIRCLE_TAG}
workflows:
  build:
    jobs:
      - build_container_image:
          filters:
            tags:
              ignore: /.*/
      - build_and_push:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
