orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
version: 2.1
jobs:
  build_container_image:
    machine:
      image: default
    steps:
      - aws-ecr/build-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: AWS_ECR_REPO_NAME
      - run:
          command: |
            docker image ls
      - run:
          name: install dockle
          command: |
            VERSION=$(
              curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
              grep '"tag_name":' | \
              sed -E 's/.*"v([^"]+)".*/\1/'
            )
            curl -LO https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
            tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
            sudo mv dockle /usr/local/bin
      - run:
          name: Scan the image with docke
          command: dockle --exit-code 1 --exit-level FATAL ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
workflows:
  build:
    jobs:
      - build_container_image:
          filters:
            tags:
              ignore: /.*/
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: AWS_ECR_REPO_NAME
          tag: ${CIRCLE_TAG}
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
