orbs:
  docker: circleci/docker@1.6.0
version: 2.1
jobs:
  build_container_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ${CIRCLE_SHA1}
workflows:
  build:
    jobs:
      - build_container_image
