orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.3
version: 2.1
jobs:
  build_scan_push:
    # docker では dockle がうまく動かないので machine を使う
    machine:
      image: default
    steps:
      - run:
          command: echo "export BRANCH_AND_COMMIT_ID=$(echo ${CIRCLE_BRANCH}-${CIRCLE_SHA1} | sed 's/\//-/g')" >> $BASH_ENV
      - aws-cli/install:
          override-installed: true
      - checkout
      - aws-ecr/build-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${BRANCH_AND_COMMIT_ID},${CIRCLE_SHA1},latest
      - run:
          command: |
            docker image ls
      - run:
          name: Install dockle
          command: |
            VERSION=$(
              curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
              grep '"tag_name":' | \
              sed -E 's/.*"v([^"]+)".*/\1/'
            )
            curl -sLO https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
            tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
            sudo mv dockle /usr/local/bin
      - run:
          command: |
            docker image inspect ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${BRANCH_AND_COMMIT_ID}
      - run:
          name: Scan the image with docke
          command: dockle --exit-code 1 --exit-level FATAL ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1}
      - run:
          name: Install trivy
          command: |
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )
            curl -sLO https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            sudo mv trivy /usr/local/bin
      - run:
          name: Scan image with trivy
          command: trivy image --ignore-unfixed --exit-code 1 --no-progress --severity HIGH,CRITICAL ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1}
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${BRANCH_AND_COMMIT_ID},${CIRCLE_SHA1},latest

  tag_push:
    machine:
      image: default
    steps:
      - aws-cli/install:
          override-installed: true
      - checkout
      - aws-ecr/ecr-login
      - aws-ecr/build-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${CIRCLE_SHA1}
          skip-when-tags-exist: true
      - run:
          name: pull image
          command: |
            docker image pull ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1}
      - run:
          name: tag image
          command: |
            docker image tag ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1} ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_TAG}
      - aws-ecr/push-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${CIRCLE_TAG}

workflows:
  build:
    jobs:
      - build_scan_push:
          filters:
            tags:
              ignore: /.*/
      - tag_push:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
