version: 2.1
jobs:
  build_container_image:
    docker:
      - image: 
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Build
          docker build . -t ${CIRCLE_SHA1}
workflows:
  build:
    jobs:
      - build_container_image
